### ISSUE TITLE
Lag for other players

### ISSUE THREAD

**Issue by jasonchitla** [arjanfrans/realtime-multiplayer-in-html5#16]
Thanks so much for the advancement of this project! Right now, I am starting up a game, then opening up a new window for another player, and when I move the other player around, it shows up laggy on the other window, even though client smoothing is on. Do you know whats going on? In the original project the interpolation was working. Maybe I have to change an option?

**Comment by jasonchitla** [comment]
i think i fixed my issue, just by changing the simulationTimestep to 1000/60 instead of 1000/66

**Comment by arjanfrans** [comment]
I experienced it myself too, but wasn't really sure where I made a mistake.
